model_name: Dr-BERT/DrBERT-7GB
per_device_eval_batch_size: 16
max_position_embeddings: 512
output_dir: "../save_models/"
data_dir: "../data/"
subset: "pos"
fewshot: 1.0
metrics: "f1"
direction: ["max","maximize"]
learning_rate: tune.loguniform(1e-5, 5e-3)
num_train_epochs:  tune.choice([1, 2])
#num_train_epochs: tune.qrandint(5, 20, 5)
gradient_accumulation_steps: tune.randint(1, 9)
weight_decay: tune.uniform(0, .5)
warmup_ratio: tune.uniform(0, .5)
dropout: tune.uniform(0, .5)
reduction_factor: 2
grace_period: 2
max_t: 100
n_trials: 6
#n_trials: 40
