model_name: Dr-BERT/DrBERT-7GB
per_device_train_batch_size: 16
max_position_embeddings: 512
output_dir: "../save_models/"
data_dir: "../data/"
subset: null
fewshot: 1.0
metrics: "f1"
direction: ["max","maximize"]
learning_rate: tune.loguniform(1e-6, 1e-4)
num_train_epochs: tune.qrandint(10, 50, 10)
gradient_accumulation_steps: tune.randint(1, 5)
weight_decay: tune.uniform(0, .5)
warmup_ratio: tune.uniform(0, .5)
dropout: tune.uniform(0, .5)
reduction_factor: 2
grace_period: 4
max_t: 100
n_trials: 20
